<?php
 define("ROOT",dirname(__FILE__));
 define("SEP",DIRECTORY_SEPARATOR);
 define("INCLUDEDIR",ROOT.SEP."includes".SEP);
 define("CONFIGDIR",ROOT.SEP."config".SEP);
 define("CONTROLLERDIR",ROOT.SEP."controllers".SEP);
 define("MODELDIR",ROOT.SEP."models".SEP);
 define("VIEWDIR",ROOT.SEP."views".SEP);
 define("HELPDIR",ROOT.SEP."helpers".SEP);
 define("MEDIADIR",ROOT.SEP."media".SEP);
 define("STATICDIR",ROOT.SEP."static".SEP);
 define("USERLIBDIR",ROOT.SEP."userlib".SEP)
?>
