<?php
 define("DB_HOST","localhost");
 define("DB_PORT","");
 define("DB_NAME","test");
 define("DB_USER","root");
 define("DB_PSWD","coolingfan");
 define("MODEL_DEBUG",TRUE);
 define("ASC",1);
 define("DESC",-1);
?>
